version: "3.0"

services:
  green:
    image: mynode:4.0
    ports:
      - "3000:3000"
    environment:
      - APP_COLOR=green
    networks:
      - mywebservice
  blue:
    image: mynode:4.0
    ports:
      - "3001:3000"
    environment:
      - APP_COLOR=blue
    networks:
      - mywebservice
  red:
    image: mynode:4.0
    ports:
      - "3002:3000"
    environment:
      - APP_COLOR=red
    networks:
      - mywebservice
  myweb:
    image: nginx:latest
    ports:
      - "80:80" 
    networks:
      - mywebservice
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./myweb.html:/usr/share/nginx/html/index.html

networks:
  mywebservice: