version: '3.1'

services:
  wordpress:
    depends_on: 
      - db
    image: wordpress
    ports: 
      - "8080:80"
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress_volume:/var/www/html

  db:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: $MYSQL_RANDOM_ROOT_PASSWORD
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  wordpress_volume:
  db_volume: